# Form implementation generated from reading ui file 'group_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupForm(object):
    def setupUi(self, GroupForm):
        GroupForm.setObjectName("GroupForm")
        GroupForm.resize(342, 137)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GroupForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=GroupForm)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.edt_name = QtWidgets.QLineEdit(parent=GroupForm)
        self.edt_name.setObjectName("edt_name")
        self.verticalLayout.addWidget(self.edt_name)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_level = QtWidgets.QLabel(parent=GroupForm)
        self.lbl_level.setWordWrap(False)
        self.lbl_level.setObjectName("lbl_level")
        self.horizontalLayout.addWidget(self.lbl_level)
        self.spn_level = QtWidgets.QSpinBox(parent=GroupForm)
        self.spn_level.setMinimum(-100)
        self.spn_level.setMaximum(100)
        self.spn_level.setObjectName("spn_level")
        self.horizontalLayout.addWidget(self.spn_level)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(GroupForm)
        QtCore.QMetaObject.connectSlotsByName(GroupForm)

    def retranslateUi(self, GroupForm):
        _translate = QtCore.QCoreApplication.translate
        GroupForm.setWindowTitle(_translate("GroupForm", "Form"))
        self.lbl_name.setText(_translate("GroupForm", "Наименование:"))
        self.lbl_level.setText(_translate("GroupForm", "Уровень"))
