# Form implementation generated from reading ui file 'position_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PositionForm(object):
    def setupUi(self, PositionForm):
        PositionForm.setObjectName("PositionForm")
        PositionForm.resize(457, 162)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PositionForm)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=PositionForm)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.edt_name = QtWidgets.QLineEdit(parent=PositionForm)
        self.edt_name.setObjectName("edt_name")
        self.verticalLayout.addWidget(self.edt_name)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_level = QtWidgets.QLabel(parent=PositionForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_level.sizePolicy().hasHeightForWidth())
        self.lbl_level.setSizePolicy(sizePolicy)
        self.lbl_level.setObjectName("lbl_level")
        self.verticalLayout_2.addWidget(self.lbl_level)
        self.cbx_level = QtWidgets.QComboBox(parent=PositionForm)
        self.cbx_level.setObjectName("cbx_level")
        self.verticalLayout_2.addWidget(self.cbx_level)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(PositionForm)
        QtCore.QMetaObject.connectSlotsByName(PositionForm)

    def retranslateUi(self, PositionForm):
        _translate = QtCore.QCoreApplication.translate
        PositionForm.setWindowTitle(_translate("PositionForm", "Form"))
        self.lbl_name.setText(_translate("PositionForm", "Наименование должности"))
        self.lbl_level.setText(_translate("PositionForm", "Уровень должности"))
